site_name: Adison's Blog
site_url: https://adisonhuang.github.io/
site_author: Adison
site_description: >-
  网站描述


# Copyright
copyright: Copyright &copy; 2020 - 2026 Adison


# Configuration
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  
  features:
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
    - search.highlight
    # - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

 # Plugins
plugins:
  - search:
      lang:
        - en


 # Customization
extra:
  analytics:
    provider: google
    property: UA-112420326-1
  #disqus: blog-lelele-ltd
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adisonhuang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/adisonhyh
    - icon: fontawesome/solid/paper-plane
      link: mailto:adison5321@gmail.com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
     alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences



# Page tree
nav:  
  - Android:
     # - android/index.md
     - 性能优化:
        - 内存优化:
          - Android内存管理: android/perf/memory/Android_memory_manager.md 
          - Android 内存分析工具(命令行): android/perf/memory/Android_memory_tools.md
          - Android 内存分析工具(查看GC): android/perf/memory/Android_memory_tools_gc.md
          - Android 内存分析工具(MAT入门): android/perf/MAT-Startup.md
          - Android 内存分析工具(MAT进阶): android/perf/MAT-Advanced.md  
          - Android句柄泄漏分析: android/perf/Android_fd_leak.md
        - 崩溃优化:
          - Android 崩溃优化: android/perf/crash/crash_op.md
          - Android 平台 Native 代码的崩溃捕获机制及实现: android/perf/crash/native-catch.md
          - native 崩溃信号介绍: android/perf/crash/native-crash-signal.md   
          - 为啥Android子线程抛出异常主线程会崩溃: android/perf/crash/KillApplicationHandler.md 
        - 启动优化:
          - Android启动优化: android/perf/launch/Android-launch-opt.md               
        - 包体积优化 :
          - Android 包体积优化: android/perf/size/Android-apk-size-opt.md
          - 从 Class 字节码入手精简 DEX 体积: android/perf/size/douyin.md  
          - Android对so体积优化的探索与实践: android/perf/size/Android-so-opt.md
        - 性能分析命令:
          - dumpsys: android/perf/dumpsys.md
          - top命令: android/perf/top.md                 
     - Android:
       - Android 动画原理: android/daily/Android_animation.md   
       - Mac10.14编译Android 8.1源码及刷入nexus 6p: android/daily/flask_android_8.md
       - APK文件分析: android/daily/apk_analyze.md
       - Android ClassLoader机制: android/daily/Android_classloader.md  
       - Android 开机流程: android/system/bootloader.md    
     - Kotlin:
       - Kotlin中inline, noinline, crossinline的区别: android/koltin/Kotlin_nline, noinline, crossinline.md
       - 使用Kotlin takeIf（或takeUnless）: android/koltin/Kotlin-takeIf-or-takeUnless.md
       - 掌握Kotlin标准函数：run, with, let, also and apply: android/koltin/Mastering Kotlin standard functions.md 
     - 并发:
       - 进程与线程的一个简单解释: android/daily/concurrency/process and thread.md 
       - 并发基础总结: android/daily/concurrency/basic.md               
  - 后端:
    - Python:  
      - python函数执行时间分析: python/python_func_time.md
      - CentOS部署flask项目: python/centos_flask.md
      - Pycharm远程调试: python/pycharm_remote_debug.md
      - 以Root权限运行/调试 PyCharm: python/PyCharm_root_debug.md
  - Native:
     - C/C++:
       - C基础知识: native/Cbasic.md
       - C++基础知识: native/C++basic.md 
       - 编译原理基础: native/compilation-principle.md
       - 深度长文教你彻底掌握C++/C指针(一):基石: native/pointer(1).md
       - 深度长文教你彻底掌握C++/C指针(二):指针和数组与字符串: native/pointer(2).md
     - JNI:
       - JNI优化: native/JNI-op.md   
     - 疑难问题:
       - dlopen时找不到__emutls_get_address符号: native/__emutls_get_address.md
             
  - 设计&架构:
    - 架构设计: design/framework design.md  
    - 六大设计原则: design/Design Principles.md
    - 设计模式概述: design/design-patterns.md
    - 设计模式:
      - 创建型模式: 
        - 概述: design/index_creational.md
        - 单例: design/singleton.md
        - 工厂模式: design/factory.md
        - 原型模式: design/prototype.md
        - 建造者模式: design/builder.md
      - 结构型模式: 
        - 概述: design/index_structural.md
        - 适配器模式: design/adapter.md
        - 代理模式: design/proxy.md
        - 外观模式: design/facade.md
        - 装饰模式: design/wrapper.md
      - 行为模式: 
        - 概述: design/index_behavioral.md
        - 策略模式: design/strategy.md  
      - 总结: design/summary.md  
    - 其他: 
      - fail-fast&fail-safe: design/fail-fast&fail-safe.md
      - 各种单例写法: design/singleton_extra.md
  - Interview: 
    - interview/index.md
    - Android:
      - Android 四大组件: interview/android_components.md
      - Android 系统原理: interview/android_sys.md 
    - Java:
      - Java 基础问题: interview/java_basic.md  
      - Java 容器问题: interview/java_collection.md  
  - 其他:  
    - shell核心语法: other/shell.md
    - 《数据结构与算法之美》笔记:
      - 复杂度分析: algo/Complexity Analysis.md
      - 数组: algo/array.md
    - 算法必知必会:  
      - 数组-实现一个支持动态扩容的数组: algo/array_algo_1.md
      - 数组-实现一个大小固定的有序数组，支持动态增删改操作: algo/array_algo_2.md
      - 数组-合并两个有序数组: algo/array_algo_3.md
    - GIT:  
      - Git submodule 子模块的管理和使用: other/git_submodule.md
