site_name: Adison's Blog
site_url: https://adisonhuang.github.io/
site_author: Adison
site_description: >-
  网站描述


# Copyright
copyright: Copyright &copy; 2020 - 2026 Adison


# Configuration
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  
  features:
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
    - search.highlight
    # - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

 # Plugins
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search:
      lang:
        - en


 # Customization
extra:
  analytics:
    provider: google
    property: UA-112420326-1
  #disqus: blog-lelele-ltd
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adisonhuang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/adisonhyh
    - icon: fontawesome/solid/paper-plane
      link: mailto:adison5321@gmail.com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
     alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences



# Page tree
nav:
  - 大前端:
    - front-end/index.md
    - Android:
      - 必知必会:
        - Android 动画原理: front-end/android/daily/Android_animation.md   
        - Android消息机制-Handler: front-end/android/system/handler.md 
        - 解析Binder框架: front-end/android/daily/binder.md   
        - APK文件分析: front-end/android/daily/apk_analyze.md 
        - Android 开机流程: front-end/android/system/bootloader.md    
        - Android Transform: front-end/android/system/android-transform.md    
        - ASM 简介: front-end/android/system/asm-basic.md    
        - ASM Core Api 详解: front-end/android/system/ASM-Core-Api.md    
      - Kotlin:
        - Kotlin中inline, noinline, crossinline的区别: front-end/android/koltin/Kotlin_nline, noinline, crossinline.md
        - 使用Kotlin takeIf（或takeUnless）: front-end/android/koltin/Kotlin-takeIf-or-takeUnless.md
        - 掌握Kotlin标准函数：run, with, let, also and apply: front-end/android/koltin/Mastering Kotlin standard functions.md 
      - 并发:
        - 线程的生命周期，真的没那么简单: front-end/android/concurrency/thread-lifecycle.md 
        - 进程与线程的一个简单解释: front-end/android/concurrency/process and thread.md 
        - 并发基础总结: front-end/android/concurrency/basic.md               
        - 线程池总结: front-end/android/concurrency/thread-pool.md 
      - JVM:
        - Java 内存区域详解: front-end/android/jvm/memory-area.md 
        - JVM 垃圾回收详解: front-end/android/jvm/jvm-garbage-collection.md 
        - Android ClassLoader机制: front-end/android/daily/Android_classloader.md
      - 杂记:
        - Mac10.14编译Android 8.1源码及刷入nexus 6p: front-end/android/daily/flask_android_8.md 
    - Flutter:
      - 使用fvm管理多个版本flutter: front-end/flutter/tools/fvm.md            
      - Dart 简介: front-end/flutter/learn/Dart.md            
  - Android性能优化:
    - perf-opt/index.md
    - 内存优化:
      - Android内存管理: perf-opt/Android/memory/Android_memory_manager.md 
      - Android 内存分析工具(命令行): perf-opt/Android/memory/Android_memory_tools.md
      - Android 内存分析工具(查看GC): perf-opt/Android/memory/Android_memory_tools_gc.md
      - Android 内存分析工具(MAT入门): perf-opt/Android/memory/MAT-Startup.md
      - Android 内存分析工具(MAT进阶): perf-opt/Android/memory/MAT-Advanced.md  
      - Android句柄泄漏分析: perf-opt/Android/memory/Android_fd_leak.md
      - Android Native 栈回溯: perf-opt/Android/memory/native-backtrace.md
      - Android内存综合治理: perf-opt/Android/memory/android-memory-gov.md
    - 崩溃优化:
      - Android 崩溃优化: perf-opt/Android/crash/crash_op.md
      - Android 平台 Native 代码的崩溃捕获机制及实现: perf-opt/Android/crash/native-catch.md
      - native 崩溃信号介绍: perf-opt/Android/crash/native-crash-signal.md   
      - 为啥Android子线程抛出异常主线程会崩溃: perf-opt/Android/crash/KillApplicationHandler.md 
    - 启动优化:
      - Android启动优化: perf-opt/Android/launch/Android-launch-opt.md               
    - 包体积优化 :
      - Android 包体积优化: perf-opt/Android/size/Android-apk-size-opt.md
      - 从 Class 字节码入手精简 DEX 体积: perf-opt/Android/size/douyin.md  
      - Android对so体积优化的探索与实践: perf-opt/Android/size/Android-so-opt.md
    - 卡顿优化:
      - Android卡顿掉帧问题分析之原理篇: perf-opt/Android/jank/jank-principle.md
      - Android卡顿掉帧问题分析之工具篇: perf-opt/Android/jank/jank-tool.md     
      - Android卡顿掉帧问题分析之实战篇: perf-opt/Android/jank/jank-shizhan.md     
      - Android卡顿优总结: perf-opt/Android/jank/jank-opt.md     
      - Linux环境下进程的CPU占用率: perf-opt/Android/jank/cpu_use.md     
    - ANR优化:
      - ANR 原理: perf-opt/Android/anr/anr.md     
    - 图片优化:
      - 图片文件技术原理: perf-opt/Android/bitmap/image.md
      - 了解各种图形格式的编码方式: perf-opt/Android/bitmap/imge-format.md
      - Bitmap从出生到死亡: perf-opt/Android/bitmap/bitmap-from-birth-to-death.md
      - Bitmap 内存占用分析: perf-opt/Android/bitmap/bitmap-memory.md
      - Glide 核心知识: perf-opt/Android/bitmap/glide.md
    - 基础:
      - native-hook: perf-opt/Android/memory/Native-Hook.md
      - dumpsys: perf-opt/Android/command/dumpsys.md
      - top命令: perf-opt/Android/command/top.md     
  - Native:
     - native/index.md
     - C/C++:
       - C基础知识: native/basic/Cbasic.md
       - C++基础知识: native/basic/C++basic.md 
       - 编译原理基础: native/basic/compilation-principle.md
       - 深度长文教你彻底掌握C++/C指针(一):基石: native/basic/pointer(1).md
       - 深度长文教你彻底掌握C++/C指针(二):指针和数组与字符串: native/basic/pointer(2).md
       - C++ auto类型推导完全攻略: native/basic/Cplus_auto.md
       - C++ decltype类型推导完全攻略: native/basic/Cplus_decltype.md
       - C++11 nullptr：初始化空指针: native/basic/Cplus_nullptr.md
       - C++11 shared_ptr智能指针: native/basic/Cplus_shared_ptr.md
     - JNI:
       - JNI优化: native/JNI/JNI-op.md   
       - JNI使用总结: native/JNI/Android-JNI.md   
     - 疑难问题:
       - dlopen时找不到__emutls_get_address符号: native/basic/__emutls_get_address.md      
  - 设计&架构:
    - design/index.md
    - 架构设计: design/design-patterns/framework design.md  
    - 六大设计原则: design/design-patterns/Design Principles.md
    - 设计模式概述: design/design-patterns/design-patterns.md
    - 设计模式:
      - 创建型模式: 
        - 概述: design/design-patterns/index_creational.md
        - 单例: design/design-patterns/singleton.md
        - 工厂模式: design/design-patterns/factory.md
        - 原型模式: design/design-patterns/prototype.md
        - 建造者模式: design/design-patterns/builder.md
      - 结构型模式: 
        - 概述: design/design-patterns/index_structural.md
        - 适配器模式: design/design-patterns/adapter.md
        - 代理模式: design/design-patterns/proxy.md
        - 外观模式: design/design-patterns/facade.md
        - 装饰模式: design/design-patterns/wrapper.md
      - 行为模式: 
        - 概述: design/design-patterns/index_behavioral.md
        - 策略模式: design/design-patterns/strategy.md  
      - 总结: design/design-patterns/summary.md  
    - 其他: 
      - fail-fast&fail-safe: design/other/fail-fast&fail-safe.md
      - 各种单例写法: design/other/singleton_extra.md
  - 面试: 
    - interview/index.md
    - Android:
      - Android 四大组件: interview/android_components.md
      - Android 屏幕适配: interview/android_screen.md
      - Android 通信相关: interview/android_communication.md
      - Android 视图相关: interview/android_view.md
      - Android 事件相关: interview/android_event.md
      - Android 系统原理: interview/android_sys.md 
    - Java:
      - Java 基础: interview/java_basic.md  
      - Java 容器: interview/java_collection.md
      - Java 多线程: interview/java_thread.md
      - Java JVM: interview/java_jvm.md
  - 计算机基础:  
    - basic/index.md
    - 操作系统:
      - shell核心语法: basic/system/shell.md
    - 网络: basic/index.md
    - 数据结构与算法:
      - 数组:  
        - 实现一个支持动态扩容的数组: basic/algo/array_algo_1.md
        - 实现一个大小固定的有序数组，支持动态增删改操作: basic/algo/array_algo_2.md
        - 合并两个有序数组: basic/algo/array_algo_3.md
      - 链表:
        - 实现单链表、循环链表、双向链表，支持增删操作: basic/algo/linklist_1.md  
        - 实现LRU缓存: basic/algo/linklist_lru.md  
        - 常见链表操作: basic/algo/linklist_2.md
      - 栈:
        - 顺序栈、链式栈: basic/algo/stack_1.md     
        - 常见栈操作: basic/algo/stack_2.md     
      - 队列:
        - 常见队列实现: basic/algo/queue.md   
      - 递归:
        - 常见递归算法: basic/algo/recursive.md  
      - 排序与二分查找: 
        - 常见排序算法: basic/algo/sort.md    
        - 二分查找算法: basic/algo/bsearch.md    
      - 散列表:
        - 常见散列表实现: basic/algo/hashTable.md
      - 二叉树:
        - 二叉查找树: basic/algo/tree.md 
      - 堆:
        - 小顶堆、大顶堆、优先级队列: basic/algo/heap.md
        - 常见堆算法: basic/algo/heap_1.md        
  - 开发工具:
    - tools/index.md  
    - GIT:  
      - Git submodule 子模块的管理和使用: tools/git/git_submodule.md 
    - VIM:  
       - Vim常用命令: tools/vim/vim-common.md 
  - 后端&运维:
    - back-end/index.md
    - Python:  
      - python函数执行时间分析: back-end/python/python_func_time.md
      - CentOS部署flask项目: back-end/python/centos_flask.md
      - Pycharm远程调试: back-end/python/pycharm_remote_debug.md
      - 以Root权限运行/调试 PyCharm: back-end/python/PyCharm_root_debug.md      
  - 游戏开发:   
    - game/index.md
    - Unity3D性能优化——工具篇: game/perf/tools.md
    - Unity3D性能优化——CPU篇: game/perf/cpu.md         
    - Unity3D性能优化——渲染篇: game/perf/render.md                 
  - 读书笔记: 
    - read/index.md 
    - 《深入理解java虚拟机》阅读笔记: read/jvm/jvm.md
    - 《数据结构与算法之美》笔记:
      - 复杂度分析: read/beautiful-algo/Complexity Analysis.md
      - 数组: read/beautiful-algo/array.md
      - 链表: read/beautiful-algo/linked-list.md  
      - 栈: read/beautiful-algo/stack.md  
      - 队列: read/beautiful-algo/queue.md  
      - 递归: read/beautiful-algo/recursion.md  
      - 基础排序算法: read/beautiful-algo/basic_sort.md   
      - 高级排序算法: read/beautiful-algo/sort-advance.md   
      - 排序优化: read/beautiful-algo/sort-op.md   
      - 二分查找: read/beautiful-algo/bsearch.md   
      - 跳表: read/beautiful-algo/skip-list.md   
      - 散列表: read/beautiful-algo/hashmap.md   
      - 哈希算法: read/beautiful-algo/hashalgo.md
      - 二叉树: read/beautiful-algo/binary-tree.md
      - 红黑树: read/beautiful-algo/Red-Black-Tree.md
      - 递归树: read/beautiful-algo/digui-tree.md
      - 堆: read/beautiful-algo/heap.md
